### PR TITLE
 fix, NS CPMG MMQ clustered fails as parameters 'dw_AB', 'dw_BC', 'dw…

### PR DESCRIPTION
**Pull request by ilsacripante**
…_AC', 'dwH_AB', 'dwH_AC', 'dwH_BC' are counted over again for each member of the cluster

### CODE REVIEW

**Comment by ilsacripante** [comment]
this should be now acceptable

**Comment by edward-dauvergne** [comment]
The commit looks good to merge (note with relax we use proper 'git merge' and not the github pull requests, but this doesn't affect your workflow).  Before I merge though, do you have an example where this fails?  This fix would be infinitely more valuable if we could first catch the failing behaviour in a minimal system test.

**Comment by ilsacripante** [comment]
Hey Edward, 
please linked [here](https://www.dropbox.com/s/2xurvmaeyg0389y/toGit.des3?dl=1) a tar file containing the minimal set you require.
Decrypt with the following command using your user-name as secret

`openssl des3 -d -k secret < file.name |tar zxf -`

command used
`mpirun -np 3  python3 relax --multi mpi4py clustered2.py`

```
relax> minimise.grid_search(lower=None, upper=None, inc=9, verbosity=1, constraints=True, skip_preset=True)


Grid search setup:  the spin block ['#solvated_mol1:265@CD1', '#solvated_mol1:298@CD1', '#solvated_mol1:298@CD2', '#solvated_mol1:324@CD2', '#solvated_mol1:368@CD1', '#solvated_mol1:347@CD2', '#solvated_mol1:334@CD1']
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Parameter    Lower bound        Upper bound        Increments         Comment           
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH            
Abort(0) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0

```

**Comment by edward-dauvergne** [comment]
Are you sure this example triggers the problem?  In Python3, the error messages appear to be suppressed (this needs to be fixed).  But in Python2, I see:

```
relax> minimise.grid_search(lower=None, upper=None, inc=9, verbosity=1, constraints=True, skip_preset=True)


Grid search setup:  the spin block ['#solvated_mol1:265@CD1', '#solvated_mol1:298@CD1', '#solvated_mol1:298@CD2', '#solvated_mol1:324@CD2', '#solvated_mol1:368@CD1', '#solvated_mol1:347@CD2', '#solvated_mol1:334@CD1']
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Parameter    Lower bound        Upper bound        Increments         Comment           
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
r2                         5.0               20.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
pA                         0.5                1.0                  9    Default bounds    
kex                        1.0            10000.0                  9    Default bounds    



Grid search setup:  the spin block ['#solvated_mol1:324@CD1']
-------------------------------------------------------------

# Parameter    Lower bound        Upper bound        Increments         Comment           
r2                         5.0               20.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
pA                         0.5                1.0                  9    Default bounds    
kex                        1.0            10000.0                  9    Default bounds    



Grid search setup:  the spin block ['#solvated_mol1:347@CD1']
-------------------------------------------------------------

# Parameter    Lower bound        Upper bound        Increments         Comment           
r2                         5.0               20.0                  9    Default bounds    
dw                       -10.0               10.0                  9    Default bounds    
dwH                       -3.0                3.0                  9    Default bounds    
pA                         0.5                1.0                  9    Default bounds    
kex                        1.0            10000.0                  9    Default bounds    





=========================================================
= Completion of the relaxation dispersion auto-analysis =
=========================================================

Elapsed time:  0.853 seconds

Traceback (most recent call last):
  File "/data/relax/relax/multi/processor.py", line 494, in run
    self.callback.init_master(self)
  File "/data/relax/relax/multi/__init__.py", line 318, in default_init_master
    self.master.run()
  File "/data/relax/relax/relax.py", line 189, in run
    self.interpreter.run(self.script_file)
  File "/data/relax/relax/prompt/interpreter.py", line 279, in run
    return run_script(intro=self.__intro_string, local=locals(), script_file=script_file, show_script=self.__show_script, raise_relax_error=self.__raise_relax_error)
  File "/data/relax/relax/prompt/interpreter.py", line 585, in run_script
    return console.interact(intro, local, script_file, show_script=show_script, raise_relax_error=raise_relax_error)
  File "/data/relax/relax/prompt/interpreter.py", line 484, in interact_script
    exec_script(script_file, local)
  File "/data/relax/relax/prompt/interpreter.py", line 363, in exec_script
    runpy.run_module(module, globals)
  File "/usr/lib64/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/relax/debugging/2018-12-18 relax disp/toGit/clustered2.py", line 191, in <module>
    Relax_disp(pipe_name=pipe_name, pipe_bundle=pipe_bundle, results_dir=RESULTS_DIR, models=MODELS, grid_inc=GRID_INC, mc_sim_num=MC_NUM, modsel=MODSEL, pre_run_dir=PRE_RUN_DIR, insignificance=INSIGNIFICANCE, numeric_only=NUMERIC_ONLY, mc_sim_all_models=MC_SIM_ALL_MODELS)
  File "/data/relax/relax/auto_analyses/relax_disp.py", line 141, in __init__
    self.run()
  File "/data/relax/relax/auto_analyses/relax_disp.py", line 625, in run
    self.optimise(model=model, model_path=model_path)
  File "/data/relax/relax/auto_analyses/relax_disp.py", line 406, in optimise
    self.interpreter.minimise.grid_search(inc=self.grid_inc)
  File "/data/relax/relax/prompt/uf_objects.py", line 224, in __call__
    self._backend(*new_args, **uf_kargs)
  File "/data/relax/relax/pipe_control/minimise.py", line 217, in grid_search
    processor.run_queue()
  File "/data/relax/relax/multi/processor.py", line 637, in run_queue
    self.run_command_queue(lqueue)
  File "/data/relax/relax/multi/processor.py", line 621, in run_command_queue
    result_queue.put(result)
  File "/data/relax/relax/multi/result_queue.py", line 92, in put
    super(Threaded_result_queue, self).put(job)
  File "/data/relax/relax/multi/result_queue.py", line 54, in put
    self.processor.process_result(job)
  File "/data/relax/relax/multi/multi_processor_base.py", line 120, in process_result
    result.run(self, memo)
  File "/data/relax/relax/multi/result_commands.py", line 141, in run
    raise self.exception
Capturing_exception: 

------------------------------------------------------------------------------------------------------------------------

  File "/data/relax/relax/multi/processor.py", line 537, in run
    command.run(self, completed)
  File "/data/relax/relax/specific_analyses/relax_disp/optimisation.py", line 654, in run
    results = grid(func=model.func, args=(), num_incs=self.inc, lower=self.lower, upper=self.upper, A=self.A, b=self.b, verbosity=self.verbosity)
  File "/usr/lib/python2.7/site-packages/minfx/grid.py", line 189, in grid
    raise MinfxError("A grid search of size %s is too large." % total_steps)


Nested Exception from sub processor
Rank: 2 Name: localhost.localdomain-pid23490
Exception type: MinfxError
Message: A grid search of size 8862938119652501095929 is too large.


------------------------------------------------------------------------------------------------------------------------



--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Setting the grid search size to 2 increments allows the script to execute.

**Comment by ilsacripante** [comment]
That was quick! 
I am also confused now. I think that this is another issue: with my fix I could get rid of another error, but the spins were first fit independently and then (with that protocol) clustered together. As far as I understand, in this case the full protocol adapts some parameters of the grid search (am I right?), and removes this "too big" grid issue.
The minimum set I sent you contains only the clustered protocol script. I am refitting them singularly and then together again and report back.

The error my correction would fix, regards the fact that in the definition of:

`def param_num(spins=None):`
in fille specific_analysis/relax_disp/params.py 

the acquisition of vector of parameters did not mention  dw/H_AB', 'dw/H_BC', 'dw/H_AC'. In that case once using the NS-MMQ models, these were loaded one by one for each member of the cluster resulting an a wrong vector shape.
You can see that in the master version dw and dwH parameters used in other models are part of the list line 919, so the error would not arise if using for instance the Analytical MMQ function.

**Comment by edward-dauvergne** [comment]
The error you fix seems correct.  I would assume it is only triggered when you cluster spins together.  I can merge the commit no problem, but what I would ideally like is to somehow catch the problem itself first.  This issue is clearly independent of parallelisation, so it should be triggered without using 'mpirun'.   Having this as a system test will completely block the bug from coming back in the future (code refactoring will often do this).  And it might catch other issues as well.

**Comment by edward-dauvergne** [comment]
This has been fixed upstream.

**Pull request closed without merging**
