### PR TITLE
Error caught in NS - MMQ cluster fit

### PR DESCRIPTION
**Pull request by ilsacripante**
ERROR CAUGHT
forgotten NS - MMQ parameters at line 920 of file specific_analyses/relax_disp/parameters.py resulted in  broken clustered MMQ fit attempts

auto_analyses/relax_disp.py is modified to improve numpy version control
all MMQ cpmgs get a None value control at the start of the function (can be removed)

### CODE REVIEW

**Comment by ilsacripante** [comment]
I was trying to fin NS MMQ clusters of fits and did have crashes during run.

**Comment by edward-dauvergne** [comment]
Hi!  Please have some patience, I'll have a look at this after the new year.  I am quite busy at the moment.  A quick look at this request shows a few issues.  Firstly you should develop in dedicated branch.  Merging from "master" is a bad idea!  Secondly, there are a lot of changes that are not related to the bug fix.  These would need to be separated out into different commits.  Cheers.

**Comment by ilsacripante** [comment]
Hey Edward,
I am fairly new to git, sorry for inconvenience. You are right, the other changes were made as I was trying to figure out why the program would crash. I will make a new commit only with the fix.

**Comment by edward-dauvergne** [comment]
Ok, I understand.  When working with git repository forks, you should keep your "master" branch clean and only perform merges from the remote's "master" to that branch.  To shift your current developments to a new branch, have a look at https://stackoverflow.com/questions/5916329/cleanup-git-master-branch-and-move-some-commit-to-new-branch.  I would then suggest creating a completely new branch for solely the bug fix, and create a new commit or set of commits there.

**Comment by edward-dauvergne** [comment]
If you can come up with small data test sets and minimal script that reproduce the error, I cannot overemphasise how useful that is compared to a direct fix.  Adding new system tests to catch the error, using the small data set and script, is invaluable.

**Comment by edward-dauvergne** [comment]
This has been fixed upstream.

**Pull request closed without merging**
